### PR TITLE
Fixed issue due to yarp::os::Vocab becoming a namespace

### PR DESCRIPTION
**Pull request by nunoguedelha**
Fixes issue https://github.com/robotology-playground/sensors-calib-inertial/issues/20.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
@lrapetti could you retest with this branch please.

**Comment by lrapetti** [comment]
I don't get any longer the error on `VOCAB`, but I get an error [here](https://github.com/robotology-playground/sensors-calib-inertial/blob/master/src/%40RemoteControlBoardRemapper/RemoteControlBoardRemapper.m#L164/RemoteControlBoardRemapper.m#L164):
```
No appropriate method, property, or field 'set' for class 'yarp.Vector'.
```

**Comment by lrapetti** [comment]
> I don't get any longer the error on `VOCAB`, but I get an error [here](https://github.com/robotology-playground/sensors-calib-inertial/blob/master/src/%40RemoteControlBoardRemapper/RemoteControlBoardRemapper.m#L164/RemoteControlBoardRemapper.m#L164):
> ```
> No appropriate method, property, or field 'set' for class 'yarp.Vector'.
> ```

Regarding this new error, the Vector.set method is missing in `yarp-matlab-bindings` branch [`bindings/regenerate`](https://github.com/robotology-playground/yarp-matlab-bindings/blob/bindings/regenerate/matlab/autogenerated/%2Byarp/Vector.m), while it is present in the [`other branches`](https://github.com/robotology-playground/yarp-matlab-bindings/blob/devel/matlab/autogenerated/+yarp/Vector.m#L140) (with other methods missing in `binding/regenerate`.

**Comment by nunoguedelha** [comment]
@lrapetti , this happens to be a **Yarp** issue, more precisely in the [`yarp.i`](https://github.com/robotology/yarp/blob/devel/bindings/yarp.i) defining extra rules for the bindings generation.

#### Short version of the cause
The line https://github.com/robotology/yarp/blob/15c3328681fc8d3da5bb3bef76d686b8fbc81d64/bindings/yarp.i#L567 is shadowing the further extensions (`%extend`) of the class `yarp::sig::Vector`, such that the extra `get`, `set`, `fromMatlab`, `toMatlab` method definitions are ignored.

#### The long version:
As you mentioned, the generated bindings currently pointed by the `devel` branch (https://github.com/robotology-playground/yarp-matlab-bindings/commit/70abe36fa84462fa53f08bd3bc1a9123c1a9d696) and the branch [bindings/regenerate](https://github.com/robotology-playground/yarp-matlab-bindings/tree/bindings/regenerate) show differences in the definition of the binding class `yarp.Vector` ([`+yarp/Vector.m`](https://github.com/robotology-playground/yarp-matlab-bindings/blob/bindings/regenerate/matlab/autogenerated/%2Byarp/Vector.m)):
- different member methods
- `get`, `set`, `toMatlab`, `fromMatlab` methods missing in the version pointed by the branch `bindings/regenerate`

This is because on `devel`, `yarp.Vector` is derived from `﻿﻿yarp.Portable`, while on `bindings/regenerate`, `yarp.Vector` is derived from `﻿﻿yarp.VectorBase`. This explains the different set of methods.
On top of that, the section [%extend yarp::sig::Vector {...}](https://github.com/robotology/yarp/blob/15c3328681fc8d3da5bb3bef76d686b8fbc81d64/bindings/yarp.i#L1069-L1080) is ignored (`get`, `set` methods missing), as well as the file [`matlab/vectors_fromTo_matlab.i`](https://github.com/robotology/yarp/blob/devel/bindings/matlab/vectors_fromTo_matlab.i) (toMatlab`, `fromMatlab` methods are missing).
This is caused by `yarp.Vector` being defined (shadowed) earlier by the line https://github.com/robotology/yarp/blob/15c3328681fc8d3da5bb3bef76d686b8fbc81d64/bindings/yarp.i#L567:
```
%template(Vector) yarp::sig::VectorOf<double>;
```
This defines `yarp.Vector` as an instance of `yarp::sig::VectorOf` which is derived from `﻿﻿yarp.VectorBase`, as mentioned before. `yarp::sig::Vector` and `yarp::sig::VectorOf<double>` are distinct classes!! Actually , `yarp::sig::Vector` has a member `VectorOf<double>`.

**Comment by nunoguedelha** [comment]
@lrapetti , I've raised an issue in **Yarp** (https://github.com/robotology/yarp/issues/1809). I will push here the new bindings, once I've done the fix on Yarp. If you feel like generating the bindings by yourself, as an exercise, you're welcome :) . I would review the changes.

**Comment by lrapetti** [comment]
I have tried to compile the bindings using https://github.com/nunoguedelha/yarp and https://github.com/robotology-playground/sensors-calib-inertial/tree/fix/vocabEncodeDecode and I confirm that the bindings for the missing methods are compiled. 
I will do some tests with the framework in order to check if everything is working correctly.

**Comment by nunoguedelha** [comment]
Great thx! Well regarding the `Vocab` and `Vector` it is working, but maybe you'll step into other similar issues..
Pay attention to the fact that the branch in my Yarp fork is on top of the latest `devel` commit.

**Comment by nunoguedelha** [comment]
BTW, I compiled the bindings with that last Yarp commit, and I realized that `IAxisInfo` class bindings were missing.
I'd rather stay on the Yarp commit a105ec3e22843434f726a6d3503eb743146fe6c1, which has the fix of `Vector` on top of the commit I gave you earlier on Friday (8c421d66b57d767f7385a56fe0b7611c8c39f975). I've pushed the respective new branch on `yarp-matlab-bindings`: `bindings/regenerate2`

**Comment by nunoguedelha** [comment]
> BTW, I compiled the bindings with that last Yarp commit, and I realized that IAxisInfo class bindings were missing.

Just saw what is causing this. This Yarp commit split a header in peaces, but the changes were not reflected in the `yarp.i`. I'm raising an issue in **Yarp** as a heads-up. The bindings generated using Yarp commit a105ec3e22843434f726a6d3503eb743146fe6c1 should still be compatible with a Yarp built on commit e876d1b.

CC @traversaro

**Comment by nunoguedelha** [comment]
Edited https://github.com/robotology-playground/sensors-calib-inertial/pull/21#issuecomment-406816992.

**Comment by nunoguedelha** [comment]
@lrapetti I need to merge to master a development branch, so I need to move on with this current PR. Since it is resolved, I'm merging. If further issues arise regarding the bindings, we'll open a new issue on this repo, or on **Yarp** directly.

**Pull request merged**
